<?xml version='1.0' encoding='ASCII'?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:ifc="https://standards.buildingsmart.org/IFC/RELEASE/IFC4/3/DEV/c2b4b18" targetNamespace="https://standards.buildingsmart.org/IFC/RELEASE/IFC4/3/DEV/c2b4b18" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="uos" type="ifc:uos" abstract="true"/>
	<xs:simpleType name="Seq-anyURI">
		<xs:list itemType="xs:anyURI"/>
	</xs:simpleType>
	<xs:complexType name="uos" abstract="true">
		<xs:sequence>
			<xs:element name="header" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" minOccurs="0"/>
						<xs:element name="time_stamp" type="xs:dateTime" minOccurs="0"/>
						<xs:element name="author" type="xs:string" minOccurs="0"/>
						<xs:element name="organization" type="xs:string" minOccurs="0"/>
						<xs:element name="preprocessor_version" type="xs:string" minOccurs="0"/>
						<xs:element name="originating_system" type="xs:string" minOccurs="0"/>
						<xs:element name="authorization" type="xs:string" minOccurs="0"/>
						<xs:element name="documentation" type="xs:string" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="optional"/>
		<xs:attribute name="express" type="ifc:Seq-anyURI" use="optional"/>
		<xs:attribute name="configuration" type="ifc:Seq-anyURI" use="optional"/>
	</xs:complexType>
	<xs:element name="ifcXML" type="ifc:ifcXML" substitutionGroup="ifc:uos"/>
	<xs:complexType name="ifcXML">
		<xs:complexContent>
			<xs:extension base="ifc:uos">
				<xs:choice minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="ifc:Entity"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="Entity" type="ifc:Entity" abstract="true" nillable="true"/>
	<xs:complexType name="Entity" abstract="true">
		<xs:attribute name="href" type="xs:anyURI" use="optional"/>
		<xs:attribute name="ref" type="xs:IDREF" use="optional"/>
		<xs:attributeGroup ref="ifc:instanceAttributes"/>
	</xs:complexType>
	<xs:attributeGroup name="instanceAttributes">
		<xs:attribute name="id" type="xs:ID" use="optional"/>
		<xs:attribute name="path" type="xs:NMTOKENS" use="optional"/>
		<xs:attribute name="pos" use="optional">
			<xs:simpleType>
				<xs:restriction>
					<xs:simpleType>
						<xs:list itemType="xs:integer"/>
					</xs:simpleType>
					<xs:minLength value="1"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:attributeGroup>
	<xs:attribute name="arraySize">
		<xs:simpleType>
			<xs:restriction>
				<xs:simpleType>
					<xs:list itemType="xs:integer"/>
				</xs:simpleType>
				<xs:minLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="itemType">
		<xs:simpleType>
			<xs:list itemType="xs:QName"/>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="cType">
		<xs:simpleType>
			<xs:list itemType="ifc:aggregateType"/>
		</xs:simpleType>
	</xs:attribute>
	<xs:simpleType name="aggregateType">
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="array"/>
			<xs:enumeration value="list"/>
			<xs:enumeration value="set"/>
			<xs:enumeration value="bag"/>
			<xs:enumeration value="array-unique"/>
			<xs:enumeration value="array-optional"/>
			<xs:enumeration value="array-optional-unique"/>
			<xs:enumeration value="list-unique"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="hexBinary">
		<xs:simpleContent>
			<xs:extension base="xs:hexBinary">
				<xs:attribute name="extraBits" type="xs:integer" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="logical">
		<xs:restriction base="xs:normalizedString">
			<xs:enumeration value="false"/>
			<xs:enumeration value="true"/>
			<xs:enumeration value="unknown"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
